### PR TITLE
Update sphere_vendors.scp

### PR DESCRIPTION
**Pull request by azmanomer**
commented 2206,2207,2272 and 2273 lines there is no description for VENDOR_B_FISHMONGER_TEMPLATE and VENDOR_S_FISHMONGER_TEMPLATE

### CODE REVIEW

**Comment by torfo** [comment]
But commenting them out is no improvement. If there is no other option, just add empty templates (probably close to VENDOR_*_FISHER) and add a TODO comment that someone else needs to come up with an item list.

**Comment by azmanomer** [comment]
i researched and its looks like they selling nothing they are just giving quest about fishing

**Comment by coruja747** [comment]
I think it's better maybe remove this npc fishmonger, this npc is a "quest giver" (not a vendor) and we dont have any quest engine on default script pack yet :P

**Comment by torfo** [comment]
@azmanomer Could you update your pull request according to @coruja747 's suggestion?

**Pull request closed without merging**
